version: 2
updates:
  # Monitor Go module dependencies
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
      # check at 3am UTC
      time: "03:00"
    open-pull-requests-limit: 10
